/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.DeThi.De04;

import javax.swing.JOptionPane;

/**
 *
 * @author Finn
 */
public class De04Form extends javax.swing.JFrame {

    /**
     * Creates new form De04Form
     */
    Dictionary d = new Dictionary();

    public De04Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNhapTu = new javax.swing.JTextField();
        btnVN = new javax.swing.JButton();
        btnUK = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Từ điểm Anh - Việt");

        jLabel2.setText("Nhập từ");

        txtNhapTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapTuActionPerformed(evt);
            }
        });

        btnVN.setText("VN");
        btnVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVNActionPerformed(evt);
            }
        });

        btnUK.setText("UK");
        btnUK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUKActionPerformed(evt);
            }
        });

        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNhapTu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVN)
                        .addGap(35, 35, 35)
                        .addComponent(btnUK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhapTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVN)
                    .addComponent(btnUK)
                    .addComponent(btnIn))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNhapTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapTuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapTuActionPerformed

    private void btnVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVNActionPerformed
        // TODO add your handling code here:
       if(!isEmpty()){
           String str1 = d.findVn(txtNhapTu.getText());
           if(str1 != null){
               JOptionPane.showConfirmDialog(null, "Nghia cua " + txtNhapTu.getText() + " la: " + str1);
           }else{
               JOptionPane.showMessageDialog(null, "Tu " + txtNhapTu.getText() + " khong co trong danh sau!, "
                       + "ban co muon them vao tu " + txtNhapTu.getText() + " vao tu diem?");
               ThemForm f = new ThemForm();
               f.setLocationRelativeTo(null);
               f.setVisible(true);
           }
       }
            
    }//GEN-LAST:event_btnVNActionPerformed

    private void btnUKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUKActionPerformed
        // TODO add your handling code here:
        if(!isEmpty()){
           String str1 = d.findEn(txtNhapTu.getText());
           if(str1 != null){
               JOptionPane.showConfirmDialog(null, "Nghia cua " + txtNhapTu.getText() + " la: " + str1);
           }else{
               JOptionPane.showMessageDialog(null, "Tu " + txtNhapTu.getText() + " khong co trong danh sau!, "
                       + "ban co muon them vao tu " + txtNhapTu.getText() + " vao tu diem?");
               ThemForm f = new ThemForm();
               f.setLocationRelativeTo(null);
               f.setVisible(true);
           }
       }
    }//GEN-LAST:event_btnUKActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        System.out.println(d.toString());
    }//GEN-LAST:event_btnInActionPerformed

    

    private boolean isEmpty() {
        return txtNhapTu.getText().equals("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(De04Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(De04Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(De04Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(De04Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new De04Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnUK;
    private javax.swing.JButton btnVN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNhapTu;
    // End of variables declaration//GEN-END:variables
}
